### ISSUE TITLE
Add cooldown for notifications

### ISSUE THREAD

**Issue by Die4Ever** [theastropath/StreamDetective#8]
If a stream is right on the edge of the 1st page, they can fall off the 1st page and then get more viewers and gets back on the 1st page again, it triggers another notification

Or if they just go offline briefly

We should have a cooldown on the notifications, which means we need to keep recently "offline" streams in the cache list, and the cache should also store a timestamp for last notification 

And/or a timestamp for last seen online and matched the conditions

**Comment by theastropath** [comment]
This will be mostly fixed when #3 gets fixed, since we won't lose track of the stream when it drops off the first page.

The cooldown part for if someone is going on/offline should be useful though.

**Comment by Die4Ever** [comment]
still need to add streams by username to the streamInfo cache so that we can save last_notified in there and actually use the cooldown properly
